version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq/
    networks:
      - sos

  sos:
    build: .
    command: sos api:stream --rabbitmq-queue tweets ${SOS_STREAM_FILTER_FILE:-/data/examples/cuba.yml}
    restart: always
    volumes:
      - .:/data
    depends_on:
      - rabbitmq
    networks:
      - sos
    env_file: .env

  sos-watcher:
    build: .
    command: sos mq:watch --queue tweets --output-path-prefix /data/out/stream
    restart: always
    volumes:
      - .:/data
    depends_on:
      - rabbitmq
    networks:
      - sos
    env_file: .env

volumes:
  rabbitmq-data:
  rabbitmq-logs:

networks:
  sos:
